import type { Metadata } from 'next';
import { Instrument_Sans, Inter, Roboto } from 'next/font/google';
import './globals.css';
import { NavBar } from '@/components/navbar/NavBar';
import GlobalContextProvider from '@/context/GlobalContextProvider';
import ErrorMessage from '@/components/errorMessage/ErrorMessage';
import Footer from '@/components/footer/Footer';

const instrumentSans = Instrument_Sans({
  variable: '--font-instrument-sans',
  subsets: ['latin'],
});
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});
const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSans.variable} ${inter.variable} ${roboto.variable} antialiased w-[100vw] relative transition-colors duration-250 overflow-x-clip`}
      >
        <GlobalContextProvider>
          <NavBar />
          {children}
          <Footer />
          <ErrorMessage />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
